### ISSUE TITLE
unknown processor architecture

### ISSUE THREAD

**Issue by wthurein** [aelve/charsetdetect-ae#4]
For 1.0.1, on a Win7 machine with Haskell Platform 7.10.2 64-bit, I had to include 'defined(__x86_64)' in libcharsetdetect/nspr-emu/prcpucfg_win.h.
Otherwise, build fails with "unknown processor architecture" (and a bunch of other stuff).
No such issue on 32-bit Haskell Platform.

**Comment by neongreen** [comment]
Thanks, fixed! (The fix is available in version 1.1.)
